version: "2"

linters:
  settings:
    errcheck:
      exclude-functions:
        - (strings.Builder).WriteString
        - (*bytes.Buffer).ReadFrom
        - io.Copy
        - fmt.Sscanf
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck

formatters:
  enable:
    - gofmt
