package setup

import (
	"bytes"
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/cloudygreybeard/jumpgate/internal/config"
)

// TemplateData holds values passed to SSH config templates.
type TemplateData struct {
	Context    string
	IsDefault  bool
	Hostname   string
	User       string
	Port       int
	SocketDir  string
	RemoteUser string
	RelayPort  int
	RemoteKey  string
}

// GenerateSSHConfig generates SSH config from templates for all contexts.
func GenerateSSHConfig(cfg *config.Config, configDir, socketDir, mode string, snippets map[string]string) error {
	var outputFile string
	if mode == "remote" {
		outputFile = filepath.Join(configDir, "ssh", "config.remote")
	} else {
		outputFile = filepath.Join(configDir, "ssh", "config.local")
	}

	if err := os.MkdirAll(filepath.Dir(outputFile), 0755); err != nil {
		return err
	}
	if err := os.MkdirAll(socketDir, 0700); err != nil {
		return err
	}

	var b strings.Builder
	b.WriteString("# Auto-generated by jumpgate from config.yaml -- do not edit manually.\n")
	b.WriteString("# Re-generate with: jumpgate setup ssh\n\n")

	var names []string
	for name := range cfg.Contexts {
		names = append(names, name)
	}

	for _, name := range names {
		rc, err := cfg.Resolve(name)
		if err != nil || rc.Context.Gate.Hostname == "" {
			continue
		}

		p := rc.Context
		data := TemplateData{
			Context:    name,
			IsDefault:  name == cfg.DefaultContext,
			Hostname:   p.Gate.Hostname,
			User:       p.Auth.User,
			Port:       p.Gate.Port,
			SocketDir:  socketDir,
			RemoteUser: p.Remote.User,
			RelayPort:  p.Relay.RemotePort,
			RemoteKey:  p.Remote.Key,
		}

		if mode == "remote" {
			writeRemoteConfig(&b, data, snippets)
		} else {
			writeLocalConfig(&b, data, snippets)
		}
	}

	if mode == "local" {
		if wc, ok := snippets["wildcard-local.conf.tpl"]; ok {
			b.WriteString(wc)
			b.WriteString("\n")
		}
	}

	if err := os.WriteFile(outputFile, []byte(b.String()), 0644); err != nil {
		return err
	}

	fmt.Printf("  Generated %s (contexts: %s)\n", outputFile, strings.Join(names, " "))
	return nil
}

func renderTemplate(name, tplStr string, data TemplateData) (string, error) {
	tmpl, err := template.New(name).Parse(tplStr)
	if err != nil {
		return "", fmt.Errorf("parsing template %s: %w", name, err)
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("executing template %s: %w", name, err)
	}
	return buf.String(), nil
}

func writeLocalConfig(b *strings.Builder, data TemplateData, snippets map[string]string) {
	if tpl, ok := snippets["gate-local.conf.tpl"]; ok {
		if out, err := renderTemplate("gate-local", tpl, data); err == nil {
			b.WriteString(out)
			b.WriteString("\n")
		}
	} else if data.IsDefault {
		writeLocalGateFallback(b, data)
	}

	if tpl, ok := snippets["remote-local.conf.tpl"]; ok {
		if out, err := renderTemplate("remote-local", tpl, data); err == nil {
			b.WriteString(out)
			b.WriteString("\n")
		}
	} else if data.IsDefault {
		writeLocalRemoteFallback(b, data)
	}
}

func writeRemoteConfig(b *strings.Builder, data TemplateData, snippets map[string]string) {
	if tpl, ok := snippets["gate-remote.conf.tpl"]; ok {
		if out, err := renderTemplate("gate-remote", tpl, data); err == nil {
			b.WriteString(out)
			b.WriteString("\n")
		}
	} else if data.IsDefault {
		writeRemoteGateFallback(b, data)
	}

	if tpl, ok := snippets["gate-relay-remote.conf.tpl"]; ok {
		if out, err := renderTemplate("gate-relay-remote", tpl, data); err == nil {
			b.WriteString(out)
			b.WriteString("\n")
		}
	} else if data.IsDefault {
		writeRemoteRelayFallback(b, data)
	}
}

// Fallback writers (used when no template file is available, for the default context only)
func writeLocalGateFallback(b *strings.Builder, d TemplateData) {
	fmt.Fprintf(b, "Host %s-gate gate\n", d.Context)
	fmt.Fprintf(b, "  HostName %s\n", d.Hostname)
	if d.User != "" {
		fmt.Fprintf(b, "  User %s\n", d.User)
	}
	if d.Port > 0 {
		fmt.Fprintf(b, "  Port %d\n", d.Port)
	}
	fmt.Fprintf(b, "  GSSAPIAuthentication yes\n")
	fmt.Fprintf(b, "  GSSAPIDelegateCredentials no\n")
	fmt.Fprintf(b, "  PreferredAuthentications gssapi-with-mic,keyboard-interactive\n")
	fmt.Fprintf(b, "  ServerAliveInterval 30\n")
	fmt.Fprintf(b, "  ControlMaster auto\n")
	fmt.Fprintf(b, "  ControlPath %s/%s-gate.sock\n", d.SocketDir, d.Context)
	fmt.Fprintf(b, "  ControlPersist 4h\n")
	b.WriteString("\n")
}

func writeLocalRemoteFallback(b *strings.Builder, d TemplateData) {
	fmt.Fprintf(b, "Host %s remote\n", d.Context)
	fmt.Fprintf(b, "  HostName localhost\n")
	if d.RemoteUser != "" {
		fmt.Fprintf(b, "  User %s\n", d.RemoteUser)
	}
	if d.RelayPort > 0 {
		fmt.Fprintf(b, "  Port %d\n", d.RelayPort)
	}
	if d.RemoteKey != "" {
		fmt.Fprintf(b, "  IdentityFile %s\n", d.RemoteKey)
	}
	fmt.Fprintf(b, "  AddKeysToAgent yes\n")
	fmt.Fprintf(b, "  UseKeychain yes\n")
	fmt.Fprintf(b, "  ProxyJump %s-gate\n", d.Context)
	b.WriteString("\n")
}

func writeRemoteGateFallback(b *strings.Builder, d TemplateData) {
	fmt.Fprintf(b, "Host %s-gate gate\n", d.Context)
	fmt.Fprintf(b, "  HostName %s\n", d.Hostname)
	if d.User != "" {
		fmt.Fprintf(b, "  User %s\n", d.User)
	}
	if d.Port > 0 {
		fmt.Fprintf(b, "  Port %d\n", d.Port)
	}
	fmt.Fprintf(b, "  GSSAPIAuthentication yes\n")
	fmt.Fprintf(b, "  GSSAPIDelegateCredentials no\n")
	fmt.Fprintf(b, "  MACs hmac-sha2-256,hmac-sha2-512\n")
	fmt.Fprintf(b, "  ServerAliveInterval 30\n")
	b.WriteString("\n")
}

func writeRemoteRelayFallback(b *strings.Builder, d TemplateData) {
	fmt.Fprintf(b, "Host %s-relay relay\n", d.Context)
	fmt.Fprintf(b, "  HostName %s\n", d.Hostname)
	if d.User != "" {
		fmt.Fprintf(b, "  User %s\n", d.User)
	}
	if d.Port > 0 {
		fmt.Fprintf(b, "  Port %d\n", d.Port)
	}
	fmt.Fprintf(b, "  GSSAPIAuthentication yes\n")
	fmt.Fprintf(b, "  GSSAPIDelegateCredentials no\n")
	fmt.Fprintf(b, "  MACs hmac-sha2-256,hmac-sha2-512\n")
	fmt.Fprintf(b, "  ServerAliveInterval 30\n")
	if d.RelayPort > 0 {
		fmt.Fprintf(b, "  RemoteForward %d localhost:22\n", d.RelayPort)
	}
	fmt.Fprintf(b, "  ExitOnForwardFailure yes\n")
	b.WriteString("\n")
}

// AddSSHInclude ensures the Include directive is in ~/.ssh/config.
func AddSSHInclude(configLocalPath string) error {
	home, _ := os.UserHomeDir()
	sshConfig := filepath.Join(home, ".ssh", "config")

	content, err := os.ReadFile(sshConfig)
	if err != nil && !os.IsNotExist(err) {
		return err
	}

	if strings.Contains(string(content), configLocalPath) {
		fmt.Println("  Include already present in ~/.ssh/config")
		return nil
	}

	newContent := fmt.Sprintf("Include %s\n\n%s", configLocalPath, string(content))
	if err := os.WriteFile(sshConfig, []byte(newContent), 0600); err != nil {
		return err
	}

	fmt.Println("  Include added to ~/.ssh/config")
	return nil
}

// EnsureSSHConfig regenerates SSH config if config.yaml is newer than the output.
func EnsureSSHConfig(cfg *config.Config, configDir, socketDir, mode string) error {
	cfgPath := filepath.Join(configDir, "config.yaml")
	var outputFile string
	if mode == "remote" {
		outputFile = filepath.Join(configDir, "ssh", "config.remote")
	} else {
		outputFile = filepath.Join(configDir, "ssh", "config.local")
	}

	cfgStat, err := os.Stat(cfgPath)
	if err != nil {
		return nil // no config file, nothing to do
	}

	outStat, err := os.Stat(outputFile)
	if err == nil && !outStat.ModTime().Before(cfgStat.ModTime()) {
		return nil // output is up to date
	}

	slog.Debug("auto-regenerating SSH config", "reason", "config.yaml is newer")

	// Load embedded snippets from the generated SSH config header won't work here,
	// but we can use the fallback templates built into the shorthand writers.
	// For full template support, the caller should pass snippets.
	return GenerateSSHConfig(cfg, configDir, socketDir, mode, nil)
}
